query GetDevice ($device: String!){
  NetworkDevice(name__value: $device) {
    edges {
      node {
        __typename
        id
        interfaces {
          edges {
            node {
              __typename
              id
              name {
                value
              }
              description {
                value
              }
              mode {
                value
              }
              status {
                value
              }
              vlan {
                edges {
                  node {
                    __typename
                    id
                    vlan_id {
                      value
                    }
                  }
                }
              }
              ip_address {
                node {
                  __typename
                  id
                  address {
                    value
                    ip
                    netmask
                    prefixlen
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  NetworkVlan {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        vlan_id {
          value
        }
      }
    }
  }
}