query MyQuery {
  NetworkDevice {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        status {
          value
        }
        description {
          value
        }
        platform {
          value
        }
        interfaces {
          edges {
            node {
              __typename
        	  id
              name {
                value
              }
              description {
                value
              }
              mode {
                value
              }
              remote_interface {
                node {
                  __typename
        		  id
                  name {
                    value
                  }
                  device {
                    node {
                      __typename
        			  id
                      name {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}