#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING, Optional

from infrahub_sdk.protocols import (
    CoreNode,
    BuiltinIPAddress,
    BuiltinIPAddressSync,
    BuiltinIPNamespace,
    BuiltinIPNamespaceSync,
    BuiltinIPPrefix,
    BuiltinIPPrefixSync,
    BuiltinTag,
    BuiltinTagSync,
    CoreAccount,
    CoreAccountGroup,
    CoreAccountGroupSync,
    CoreAccountRole,
    CoreAccountRoleSync,
    CoreAccountSync,
    CoreAction,
    CoreActionSync,
    CoreArtifact,
    CoreArtifactCheck,
    CoreArtifactCheckSync,
    CoreArtifactDefinition,
    CoreArtifactDefinitionSync,
    CoreArtifactSync,
    CoreArtifactTarget,
    CoreArtifactTargetSync,
    CoreArtifactThread,
    CoreArtifactThreadSync,
    CoreArtifactValidator,
    CoreArtifactValidatorSync,
    CoreBasePermission,
    CoreBasePermissionSync,
    CoreChangeComment,
    CoreChangeCommentSync,
    CoreChangeThread,
    CoreChangeThreadSync,
    CoreCheck,
    CoreCheckDefinition,
    CoreCheckDefinitionSync,
    CoreCheckSync,
    CoreComment,
    CoreCommentSync,
    CoreCredential,
    CoreCredentialSync,
    CoreCustomWebhook,
    CoreCustomWebhookSync,
    CoreDataCheck,
    CoreDataCheckSync,
    CoreDataValidator,
    CoreDataValidatorSync,
    CoreFileCheck,
    CoreFileCheckSync,
    CoreFileThread,
    CoreFileThreadSync,
    CoreGeneratorAction,
    CoreGeneratorActionSync,
    CoreGeneratorCheck,
    CoreGeneratorCheckSync,
    CoreGeneratorDefinition,
    CoreGeneratorDefinitionSync,
    CoreGeneratorGroup,
    CoreGeneratorGroupSync,
    CoreGeneratorInstance,
    CoreGeneratorInstanceSync,
    CoreGeneratorValidator,
    CoreGeneratorValidatorSync,
    CoreGenericAccount,
    CoreGenericAccountSync,
    CoreGenericRepository,
    CoreGenericRepositorySync,
    CoreGlobalPermission,
    CoreGlobalPermissionSync,
    CoreGraphQLQuery,
    CoreGraphQLQueryGroup,
    CoreGraphQLQueryGroupSync,
    CoreGraphQLQuerySync,
    CoreGroup,
    CoreGroupAction,
    CoreGroupActionSync,
    CoreGroupSync,
    CoreGroupTriggerRule,
    CoreGroupTriggerRuleSync,
    CoreIPAddressPool,
    CoreIPAddressPoolSync,
    CoreIPPrefixPool,
    CoreIPPrefixPoolSync,
    CoreMenu,
    CoreMenuItem,
    CoreMenuItemSync,
    CoreMenuSync,
    CoreNodeSync,
    CoreNodeTriggerAttributeMatch,
    CoreNodeTriggerAttributeMatchSync,
    CoreNodeTriggerMatch,
    CoreNodeTriggerMatchSync,
    CoreNodeTriggerRelationshipMatch,
    CoreNodeTriggerRelationshipMatchSync,
    CoreNodeTriggerRule,
    CoreNodeTriggerRuleSync,
    CoreNumberPool,
    CoreNumberPoolSync,
    CoreObjectComponentTemplate,
    CoreObjectComponentTemplateSync,
    CoreObjectPermission,
    CoreObjectPermissionSync,
    CoreObjectTemplate,
    CoreObjectTemplateSync,
    CoreObjectThread,
    CoreObjectThreadSync,
    CorePasswordCredential,
    CorePasswordCredentialSync,
    CoreProfile,
    CoreProfileSync,
    CoreProposedChange,
    CoreProposedChangeSync,
    CoreReadOnlyRepository,
    CoreReadOnlyRepositorySync,
    CoreRepository,
    CoreRepositoryGroup,
    CoreRepositoryGroupSync,
    CoreRepositorySync,
    CoreRepositoryValidator,
    CoreRepositoryValidatorSync,
    CoreResourcePool,
    CoreResourcePoolSync,
    CoreSchemaCheck,
    CoreSchemaCheckSync,
    CoreSchemaValidator,
    CoreSchemaValidatorSync,
    CoreStandardCheck,
    CoreStandardCheckSync,
    CoreStandardGroup,
    CoreStandardGroupSync,
    CoreStandardWebhook,
    CoreStandardWebhookSync,
    CoreTaskTarget,
    CoreTaskTargetSync,
    CoreThread,
    CoreThreadComment,
    CoreThreadCommentSync,
    CoreThreadSync,
    CoreTransformJinja2,
    CoreTransformJinja2Sync,
    CoreTransformPython,
    CoreTransformPythonSync,
    CoreTransformation,
    CoreTransformationSync,
    CoreTriggerRule,
    CoreTriggerRuleSync,
    CoreUserValidator,
    CoreUserValidatorSync,
    CoreValidator,
    CoreValidatorSync,
    CoreWebhook,
    CoreWebhookSync,
    InternalAccountToken,
    InternalAccountTokenSync,
    InternalRefreshToken,
    InternalRefreshTokenSync,
    IpamNamespace,
    IpamNamespaceSync,
    LineageOwner,
    LineageOwnerSync,
    LineageSource,
    LineageSourceSync,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        AnyAttribute,
        AnyAttributeOptional,
        String,
        StringOptional,
        Integer,
        IntegerOptional,
        Boolean,
        BooleanOptional,
        DateTime,
        DateTimeOptional,
        Dropdown,
        DropdownOptional,
        HashedPassword,
        HashedPasswordOptional,
        MacAddress,
        MacAddressOptional,
        IPHost,
        IPHostOptional,
        IPNetwork,
        IPNetworkOptional,
        JSONAttribute,
        JSONAttributeOptional,
        ListAttribute,
        ListAttributeOptional,
        URL,
        URLOptional,
    )


class CoreWeightedPoolResource(CoreNode):
    allocation_weight: IntegerOptional
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class NetworkDevice(CoreArtifactTarget):
    description: StringOptional
    name: String
    password: StringOptional
    platform: String
    port: IntegerOptional
    status: Dropdown
    user: StringOptional
    artifacts: RelationshipManager
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class IpamIPPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: BooleanOptional
    is_top_level: BooleanOptional
    member_type: DropdownOptional
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    utilization: IntegerOptional
    children: RelationshipManager
    ip_addresses: RelationshipManager
    ip_namespace: RelatedNode
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    resource_pool: RelationshipManager
    subscriber_of_groups: RelationshipManager


class NetworkInterface(CoreNode):
    description: StringOptional
    mode: Dropdown
    name: String
    status: Dropdown
    device: RelatedNode
    ip_address: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    vlan: RelationshipManager


class NetworkVlan(CoreNode):
    name: String
    status: Dropdown
    vlan_id: Integer
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkDevice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    password: StringOptional
    port: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    user: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkVlan(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
