# yamllint disable rule:line-length
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    inherit_from: ["CoreArtifactTarget"]
    display_labels:
      - "name__value"
    icon: "mdi:router-network"
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: platform
        kind: Text
        optional: false
      - name: user
        kind: Text
        optional: true
      - name: password
        kind: Password
        optional: true
      - name: port
        kind: Number
        optional: true
      # connection_options
      - name: status
        kind: Dropdown
        choices:
          - name: active
            label: Active
            description: "Device is active"
            color: "#7fbf7f"
          - name: maintenance
            label: Maintenance
            description: "Device is in maintenance"
            color: "#ffd27f"
          - name: offline
            label: Offline
            description: "Device is offline"
            color: "#bfbfbf"
    relationships:
      - name: interfaces
        identifier: "device__interface"
        cardinality: many
        peer: NetworkInterface
        kind: Component

  - name: Interface
    namespace: Network
    include_in_menu: true
    icon: "mdi:ethernet"
    display_labels:
      - "name__value"
      # - "mode__value"
    uniqueness_constraints:
      - ["device", "name__value"]
    human_friendly_id:
      - device__name__value
      - name__value
    attributes:
      - name: name
        kind: Text
      - name: description
        kind: Text
        optional: true
      - name: mode
        label: Mode
        kind: Dropdown
        choices:
          - name: access
            label: Access
            description: "Access port"
            color: "#7fbf7f"
          - name: none
            label: None
            description: "None port"
            color: "#7f7f7f"
          - name: trunk
            label: Trunk
            description: "Trunk port"
            color: "#f7cf6a"
          - name: routed
            label: Routed
            description: "Routed L3 port"
            color: "#fcba03"
          - name: fabric
            label: Fabric
            description: "IPv6 Fabric port"
            color: "#42f2f5"
      - name: status
        kind: Dropdown
        choices:
          - name: up
            label: Up
            description: "Interface is operational"
            color: "#4caf50"
          - name: down
            label: Down
            description: "Interface is not operational(shut down)"
            color: "#f44336"
    relationships:
      - name: device
        peer: NetworkDevice
        identifier: "device__interface"
        optional: false
        cardinality: one
        kind: Parent
      - name: ip_address
        peer: IpamIPAddress
        cardinality: one
        optional: true
        kind: Attribute
      - name: vlan
        peer: NetworkVlan
        identifier: "interface__vlan"
        optional: true
        cardinality: many
        kind: Attribute
        description: "VLANs associated with this interface"
      - name: remote_interfaces
        peer: NetworkInterface
        optional: true
        cardinality: one
        kind: Attribute

  # VLAN
  - name: Vlan
    namespace: Network
    icon: "mdi:cloud"
    display_labels:
      - "name__value"
      - "vlan_id__value"
    attributes:
      - name: name
        kind: Text
        description: "VLAN Name"
      - name: vlan_id
        kind: Number
        unique: true
        description: "VLAN ID"
      - name: status
        kind: Dropdown
        choices:
          - name: active
            label: Active
            color: "#7fbf7f"
          - name: inactive
            label: Inactive
            color: "#bfbfbf"
        description: "Status of the VLAN"

  - name: IPPrefix
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPPrefix"
    description: "IPv4 or IPv6 network"
    label: "IP Prefix"

  - name: IPAddress
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPAddress"
    description: "IP Address"
    label: "IP Address"

  # Used for global artifacts
  - name: Global
    namespace: Topology
    description: "A Node used for global artifacts"
    human_friendly_id: ["name__value"]
    include_in_menu: false
    inherit_from:
      - CoreArtifactTarget
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
