---
x-infrahub-custom-build: &infrahub_custom_build
  image: custom/infrahub-worker:${INFRAHUB_BASE_VERSION:-1.4.3}
  build:
    context: infrahub-worker
    dockerfile: Dockerfile
    args:
      INFRAHUB_BASE_VERSION: "${INFRAHUB_BASE_VERSION:-1.4.3}"

services:
  infrahub-server:
    <<: *infrahub_custom_build
  task-worker:
    <<: *infrahub_custom_build
  task-manager:
    <<: *infrahub_custom_build