services:
  prefect-database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    volumes: 
      - prefect-db:/var/lib/postgresql/data
  prefect-server:
    image: prefecthq/prefect:3-latest
    restart: always
    volumes:
      - prefect:/root/.prefect
    ports:
      - "4200:4200"
    command: prefect server start
    depends_on:
      - prefect-database
    environment:
      - PREFECT_UI_URL=http://prefect-server:4200/api
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect-database:5432/prefect
  # ToDo: worker for GitOps tasks
  gitops-worker:
    image: prefecthq/prefect:3-python3.12
    command: prefect worker start --pool gitops-worker --with-healthcheck
    restart: unless-stopped
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
